src/Entity/Cible.php
<?php

namespace App\Entity;

use App\Repository\CibleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CibleRepository::class)
 */
class Cible
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $nom;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank()
     */
    private $DateNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $nomCode;

    /**
     * @ORM\ManyToOne(targetEntity=Nationnalite::class, inversedBy="cibles")
     * @Assert\NotBlank()
     */
    private $nationnalite;

    /**
     * @ORM\ManyToMany(targetEntity=Mission::class, mappedBy="Cible")
     * @ORM\JoinColumn(onDelete="SET NULL")
     * @Assert\NotBlank()
     */
    private $mission;

    public function __construct()
    {
        $this->mission = new ArrayCollection();
    }

    /**
     * @Assert\Callback
     */
    public function validationNationnaliteCibleMission(ExecutionContextInterface $context)
    {
        $bool = false;
        if($this->getMissions() !== null)
        foreach($this->getMissions() as $mission){
           if($mission->getPays()->getNom() !== $this->getNationnalite()->getPays()->getNom()){
               $bool = true;
           }
        }
        if($bool == true){
            $context->buildViolation('Impossible d\' ajouter ou de modifier cette Cible car la nationnalité selectionné est différente de celle du pays de la mission')->addViolation();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->DateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $DateNaissance): self
    {
        $this->DateNaissance = $DateNaissance;

        return $this;
    }

    public function getNomCode(): ?string
    {
        return $this->nomCode;
    }

    public function setNomCode(string $nomCode): self
    {
        $this->nomCode = $nomCode;

        return $this;
    }

    public function getNationnalite(): ?Nationnalite
    {
        return $this->nationnalite;
    }

    public function setNationnalite(?Nationnalite $nationnalite): self
    {
        $this->nationnalite = $nationnalite;

        return $this;
    }

    /**
     * @return Collection|Mission[]
     */
    public function getMissions(): Collection
    {
        return $this->mission;
    }

    public function setMission(?Mission $mission): self
    {
        $this->mission = $mission;

        return $this;
    }

    public function addMission(Mission $mission): self
    {
        if (!$this->mission->contains($mission)) {
            $this->mission[] = $mission;
            $mission->addCible($this);
        }

        return $this;
    }

    public function removeMission(Mission $mission): self
    {
        $this->mission->removeElement($mission);
        $mission->removeCible($this);

        return $this;
    }

    /**
     * @return Collection|Mission[]
     */
    public function getMission(): Collection
    {
        return $this->mission;
    }
}

src/Form/CibleType.php
<?php

namespace App\Form;

use App\Entity\Cible;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Mission;
use App\Entity\Nationnalite;
class CibleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class)
            ->add('prenom', TextType::class)
            ->add('DateNaissance', BirthdayType::class)
            ->add('nomCode', TextType::class)
            ->add('nationnalite', EntityType::class,
            array('class' => Nationnalite::class,
                  'choice_label' => 'nomNatio',
                  'multiple' => false,
                  'expanded' => false
                  ))
            ->add('mission', EntityType::class,
            array('class' => Mission::class,
                  'choice_label' => 'titre',
                  'multiple' => true,
                  'expanded' => false,
                  'required' => false,
                  ))
            ->add('Sauvegarde', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Cible::class,
        ]);
    }
}

src/Controller/CibleController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Cible;
use App\Entity\Mission;
use App\Form\CibleType;

class CibleController extends AbstractController
{
    /**
     * @Route("/cible", name="cible")
     */
    public function index()
    {
        //On récupere l'entity manager
        $em = $this->getDoctrine()->getManager();
        //On récupere le repository de la classe Cible
        $cibleRepository = $em->getRepository(Cible::class);
        //On récupere toutes les cibles présentent dans la base de données
        $listeCible = $cibleRepository->findAll();
        //On affiche toute les cibles
        return $this->render('cible/index.html.twig', [
            'listeCible'=>$listeCible
        ]);
    }

    /**
     * @Route("cible-ajout", name="cible-ajout")
     */
    public function ajout(Request $request)
    {
        //On créer une nouvelle cible
        $cible = new Cible();
        //On créer un nouveau formulaire qui utiliseras le FormType de Cible
        $form = $this->createForm(CibleType::class, $cible);
        //On regarde si le formulaire a été envoyé avec une methode post
        if($request->isMethod('POST')){
            $form->handleRequest($request);
            //On vérifie que le formulaire a bien été envoyé et qu'il est valide
            if($form->isSubmitted() && $form->isValid()){
                //On récupere l'entity manager
                $em = $this->getDoctrine()->getManager();
                //On enregistre la nouvelle cible dans la base de données
                $em->persist($cible);
                $em->flush();
                //On redirige sur la page qui affiche tout les agents
                return $this->redirectToRoute('cible');
            }
        }
        //On affiche la page du fomulaire
        return $this->render('cible/ajout.html.twig', ['cible'=> $cible, 'form' => $form->createView()]);
    }

    /**
     * @Route("cible-suppression/{id}", name="cible-suppression")
     */
    public function suppression(int $id)
    {
        //On récupere l'entity manager
        $em = $this->getDoctrine()->getManager();
        //On récupere le repository de la classe Cible
        $cibleRepository = $em->getRepository(Cible::class);
        //On récupere la cible a supprimé avec l'identifiant dans l'url
        $suppressionCible = $cibleRepository->find($id);
        //On verifie que la cible existe
        if($suppressionCible === null){
            throw new NotFoundHttpException("La cible d'id ".$id." n'existe pas");
        }
        foreach($suppressionCible->getMissions() as $mission){
            $suppressionCible->removeMission($mission);
        }
        //On supprime l'agent de la base de données
        $em->remove($suppressionCible);
        $em->flush();
        //On redirige sur la page qui affiche toutes les cibles
        //return $this->redirectToRoute('cible');
    }

    /**
     * @Route("cible-details/{id}", name="cible-details")
     */
    public function detail(int $id)
    {
        //On récupere l'entity manager
        $em = $this->getDoctrine()->getManager();
        //On récupere le repository de la classe Cible
        $cibleRepository = $em->getRepository(Cible::class);
        $detailCible = $cibleRepository->find($id);        
        return $this->render('cible/detail.html.twig', ['detailCible' => $detailCible]);
    }

    /**
     * @Route("cible-modification/{id}", name="cible-modification")
     */
    public function modifier(int $id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $cibleRepository = $em->getRepository(Cible::class);
        $modificationCible = $cibleRepository->find($id);

        if($modificationCible === null){
            throw new NotFoundHttpException("La cible d'id ".$id." n'existe pas");
        }
        $form = $this->createForm(CibleType::class, $modificationCible);
        if($request->isMethod('POST')){
            $form->handleRequest($request);
            if($form->isSubmitted() && $form->isValid()){
                $em->persist($modificationCible);
                $em->flush();
                return $this->redirectToRoute('cible-details', ['id' => $modificationCible->getId()]);
            }
        }
        return $this->render('cible/modification.html.twig', array('form' => $form->createView(), 'modificationCible' => $modificationCible));
    }


}

templates/cible/ajout.html.twig
{% extends "basetemplate.html.twig" %}
{% block title%}

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
<div class="row justify-content-around">
    <div class="col-10">
        <div class="pull-right">
        </div>
        <h1 class="text-center">Ajouter une cible</h1>
        <hr class="my-5">

        <a href="{{ path('cible') }}" class="link-secondary text-decoration-none mb-4">← Retour</a>

        {{ include('cible/formulaireCible.html.twig')}}
        
        <a href="{{ path('cible') }}" class="link-secondary text-decoration-none mb-4">← Retour</a>
    </div>
</html>

{% block JS %}
    {{ parent() }}
{% endblock %}

{% endblock %}

templates/cible/detail.html.twig
{% extends "basetemplate.html.twig" %}
{% block title%}

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
<div class="row justify-content-around">
    <div class="col-10 text-center">
        <div class="pull-right">
        </div>
        
        <h1 class="my-5">Détails de la cible : {{ detailCible.nom }} {{ detailCible.prenom }}</h1>
        <hr class="my-3">

        <div class="row my-5 justify-content-evenly">
            <div class="col-5 bg-light shadow rounded p-4">
                <div class="text-center">
                    <h4>Infos Cible</h4>
                    <hr class="bg-primary text-primary">
                </div>
                <p>Nom de code cible : {{ detailCible.nomCode }}</p>
                <p>Date de naissance : {{ detailCible.DateNaissance|date("Y-m-d") }}</p>
                <p>Nationalité : 
                    {% if detailCible.nationnalite is null %}
                        Aucune nationnalité attribuée
                    {% else %}
                        {{ detailCible.nationnalite.nomNatio }}
                    {% endif %}
                </p>
            </div>
            <div class="col-4 bg-light shadow rounded p-4">
                <div class="text-center">
                    <h4>Missions</h4>
                    <hr class="bg-primary text-primary">
                </div>
                <p>{% for mission in detailCible.missions %} - <a href="{{ path('mission-details', {id: mission.id}) }}">{{ mission.titre }}</a> <br/>{% else %} Aucune mission {% endfor %}</p>
            </div>
        </div>

        <a href ="{{ path('cible-modification', {id: detailCible.id}) }}" class ="my-5 btn btn-primary">Modifier Cible</a>

    </div>
</div>
</html>
{% endblock %}

templates/cible/formulaireCible.html.twig
<div>
<div class="pull-right">
</div>
    <div class="well">
        {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
        
        {# Les erreurs générales du formulaire #}
        {{ form_errors(form) }}

        {# Génération manuelle du formulaire #}
        {# Nom de la cible #}
        <div class="form-group my-5">
            {# Génération du label #}
            {{ form_label(form.nom, "Nom de la cible", {'label_attr': {'class': 'cal-sm-2 control-label'}}) }}
            {# Affichage des erreurs pour ce champ précis #}
            {{ form_errors(form.nom) }}
            <div>
                {# Génération de l'input. #}
                {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        {# Prénom de la cible #}
        <div class="form-group my-5">
            {# Génération du label #}
            {{ form_label(form.prenom, "Prénom de la cible", {'label_attr': {'class': 'cal-sm-2 control-label'}}) }}
            {# Affichage des erreurs pour ce champ précis #}
            {{ form_errors(form.prenom) }}
            <div>
                {# Génération de l'input. #}
                {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        {# Date de Naissance de la cible #}
        <div class="form-group my-5">
            {# Génération du label #}
            {{ form_label(form.DateNaissance, "Date de naissance de la cible", {'label_attr': {'class': 'cal-sm-2 control-label'}}) }}
            {# Affichage des erreurs pour ce champ précis #}
            {{ form_errors(form.DateNaissance) }}
            <div>
                {# Génération de l'input. #}
                {{ form_widget(form.DateNaissance, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        {# Nom de code de la cible #}
        <div class="form-group my-5">
            {# Génération du label #}
            {{ form_label(form.nomCode, "Nom de code de la cible", {'label_attr': {'class': 'cal-sm-2 control-label'}}) }}
            {# Affichage des erreurs pour ce champ précis #}
            {{ form_errors(form.nomCode) }}
            <div>
                {# Génération de l'input. #}
                {{ form_widget(form.nomCode, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        {# Mission de la cible #}
        <div class="form-group my-5">
            {# Génération du label #}
            {{ form_label(form.mission, "Missions de la cible", {'label_attr': {'class': 'cal-sm-2 control-label'}}) }}
            {# Affichage des erreurs pour ce champ précis #}
            {{ form_errors(form.mission) }}
            <div>
                {# Génération de l'input. #}
                {{ form_widget(form.mission, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        {# Nationnalité de la cible #}
        <div class="form-group my-5">
            {# Génération du label #}
            {{ form_label(form.nationnalite, "Nationnalité de la cible ", {'label_attr': {'class': 'cal-sm-2 control-label'}}) }}
            {# Affichage des erreurs pour ce champ précis #}
            {{ form_errors(form.nationnalite) }}
            <div>
                {# Génération de l'input. #}
                {{ form_widget(form.nationnalite, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <p>
        {# Génération automatique des champs pas encore écrits #}
        {{ form_rest(form) }}
        {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
        {{ form_widget(form.Sauvegarde, {'attr': {'class': 'btn btn-primary'}}) }}
        {# Fermeture de la balise <form> de formulaire HTML #}
        {{ form_end(form) }}
    </div>
</html>

templates/cible/index.html.twig
{% extends "basetemplate.html.twig" %}
{% block title%}

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
<div>
    <div class="pull-right">
    </div>

    <div class="row justify-content-around">
        <div class="col-10 text-center">
            <h1>Cibles</h1>
            <hr class="my-5">

            <a href ="{{ path('cible-ajout')}}" class ="btn btn-dark mb-4">Ajouter une Cible</a>
        </div>
    </div>

    <div class="row">
        <div class="col-12 shadow rounded table-hover p-3">
            <table id="table" class="table table-striped table-light text-center">
                <thead class="table-dark">
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Code d'identification</th>
                        <th>Date de Naissance</th>
                        <th>Nationnalité</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cible in listeCible %}
                    <tr>
                        <td>{{ cible.nom }}</td>
                        <td>{{ cible.prenom }}</td>
                        <td>{{ cible.nomCode }}</td>
                        <td>{{ cible.DateNaissance|date('Y-m-d') }}</td>
                        {% if cible.nationnalite is null %}
                            <td>Aucune nationnalité attribuée</td>
                        {% else %}
                            <td>{{ cible.nationnalite.nomNatio }}</td>
                        {% endif %}
                        <td>
                            <a class="btn btn-primary" title="Détails" href="{{ path('cible-details', {id: cible.id}) }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-card-checklist" viewBox="0 0 16 16">
                                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                                    <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z"/>
                                </svg>
                            </a>
                            <a class="suppression btn btn-danger" title="Supprimer" data-playground-id="{{ cible.id }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                </svg>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $(".suppression").click(function(){
            var id = $(this).attr("data-playground-id");
            var url = '{{path('cible-suppression', { 'id': 0}) }}';
            var url = url.replace("0",id);
            $.ajax({
                url: url,
                type: 'delete',
                success:function(data){
                    console.log(data);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
            $(this).closest("tr").hide();
        });
    });
</script>
</html>
{% endblock %}

templates/cible/modification.html.twig
{% extends "basetemplate.html.twig" %}
{% block title%}

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
<div class="row justify-content-around">
    <div class="col-10">
        <div class="pull-right">
        </div>

        <h1 class="text-center">Modification Cible : {{ modificationCible.nom }} {{ modificationCible.prenom }}</h1>
        <hr class="my-5">

        {{ include('cible/formulaireCible.html.twig')}}

        <p class="my-5"><a href="{{ path('cible-details', {'id': modificationCible.id}) }}" class="link-secondary text-decoration-none">← Retour</a></p>

    </div>
</html>

{% block JS %}
    {{ parent() }}
{% endblock %}

{% endblock %}